### ISSUE TITLE
[Suggestion] Using worker thread for calculation

### ISSUE THREAD

**Issue by MuTsunTsai** [origamimagiro/flat-folder#15]
Hello and I just found this cool project of yours; pretty impressive! I have one humble suggestion. For now everything runs in the UI thread, which could block user interactions for Ryujin-type CPs. It would be better if you could put the calculation-heavy parts in a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) so that the UI thread is not blocked. In fact I'm also working on implementing this for the next version of BP Studio.

**Comment by origamimagiro** [comment]
Yup, thanks for the suggestion! This is already a planned improvement, but thanks for making it an issue to track! :)
