### ISSUE TITLE
Wrong names in examples_data.csv

### ISSUE THREAD

**Issue by Ooouch1** [origamimagiro/flat-folder#32]
I found errors as below:

* Koti IMAI -> Kota IMAI
* Morisue KEI -> Kei MORISUE

Japanese name is difficult 🙃

**Comment by origamimagiro** [comment]
Ugh, first one was a typo, second one was inexcusable. Thank you for pointing out! Fixed in 41eef2287aba2ac0f4ba2e5a52089bafc00b6e33
