### ISSUE TITLE
UTF-16 code points and indexing limit

### ISSUE THREAD

**Issue by origamimagiro** [origamimagiro/flat-folder#42]
Flat-Folder's currently tries to efficiently encode integers as strings by encoding them into UTF16 code points. However, the 2048 code points from U+D800 to U+DFFF (55296 to 57343) are reserved as surrogate pairs, and thus cannot be represented this way (whoops). This can make Flat-Folder crash when there are more than 55296 of some indexed element. An easy fix would be to just offset the conversion range by 57344 (0xE000) so that all code points will be valid up 1114111 (0x10FFFF), allowing us to encode 1114111 - 57343 = 1056768 integers (much better than 55296). But perhaps there are better ways of encoding integers as strings...

**Comment by OrigamiDraw** [comment]
Coincidentally, we were dealing with the same problem, but at the next level. For very complex CPs, even this new limit of 1,056,768 is not sufficient. We propose another encoding which pushes the limit to 2^31=2,147,483,648. Instead of using a single UTF32 character, we use one or two UTF16 characters, each of which has a complete range of 65,536 charcodes. We just lose one bit to signal whether the code uses one or two characters.

**Comment by origamimagiro** [comment]
Oh nice! To clarify, we were not using UTF32 characters, just standard [UTF16 code point encodings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters), delegating to the native string processor to encode larger numbers into two UTF16 code units that are surrogate pairs. But of course your encoding is much more efficient, allowing a much larger range as you've noted. So I definitely think we should switch to your encoding!

I will note that I was at first suspicious of your method because encoding an arbitrary sequence of 16-bit values as UTF16 code units could lead to a UTF16 string that is not [wellformed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed), since it could contain lone surrogates. However, apparently, Javascript allows for the representation of sequences of UTF16 code units that are not well formed, though of course they will break APIs where a well formed UTF16 string is expected, like with [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder). But since we don't use these strings for anything other than compression and as keys in hash tables, I don't think there's any problem for us encoding strings that are not well formed.

**Comment by OrigamiDraw** [comment]
Indeed, this [Unicode terminology](https://www.unicode.org/faq/utf_bom.html) still baffles me. But I think I've got it now.
